name: CI DevOps

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-job:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout do código
          uses: actions/checkout@v4
        - name: Simular Build
          run: echo "Olá, ${{ github.actor }}! Iniciando build"
  analyze:
    name: Analyze (SAST)
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:python"

  check-sast-report:
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Validar Relatório SAST
        run: |
          echo "No GitHub, as vulnerabilidades ficam em Security > Code Scanning"
          echo "Executando script de validação customizado..."
          python3 -c "
          import os
          print('Análise de segurança concluída com sucesso.')
          "        
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências (Flask e Coverage)
        run: pip install flask coverage

      - name: Rodar testes com Coverage
        run: python -m coverage run -m unittest -v tests/appTest.py

      - name: Exibir relatório de cobertura
        run: python -m coverage report

  test-job2:
    runs-on: ubuntu-latest
    steps:
      - name: Teste 2
        run: echo "Executando o test-job2 da Ação 1"